# Generated by Django 6.0.7 on 2026-07-16 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='RegisteredClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('brand', models.CharField(default='Apple', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(upload_to='products/')),
                ('storage', models.CharField(help_text='e.g. 256GB, 512GB, 1TB', max_length=50)),
                ('ram', models.CharField(blank=True, help_text='e.g. 12GB', max_length=50, null=True)),
                ('color', models.CharField(help_text='e.g. Cosmic Orange, Deep Blue, Silver', max_length=50)),
                ('warranty_info', models.CharField(default='2-year device + 6-month screen warranty', max_length=200)),
                ('stock', models.PositiveIntegerField(default=5)),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_top_deal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='apex_mobile.category')),
            ],
        ),
    ]
